CHANNEL_CONFIGS = {
    "military": {
        "channel_handle": "@MilitaryDeepOps",
        "thumbnail_palette": "red_white",
        "thumbnail_add_arrow": True,
        "thumbnail_add_circle": False,
        "thumbnail_hook_pool": "military_ops",
        "script_tone": "classified_documentary",
        "script_structure": "four_act_shock",
        "bg_contrast_boost": 1.5,
        "bg_pool": "military_combat",
        "bg_blacklist": "-civilian -commercial -protest -vintage -antique -parade",
        "title_formula": "dramatic_revelation",
        "video_duration_target": 105,  # seconds
        "cta_style": "provocative_question",
    },
    "aviation": {
        "channel_handle": "@CivilAviationLords",
        "youtube_channel_id": "UC4fvqczFilwYTswXQMM0zJA",
        "thumbnail_palette": "yellow_orange",
        "thumbnail_add_arrow": False,
        "thumbnail_add_circle": True,
        "thumbnail_hook_pool": "aviation_disaster",
        "script_tone": "aviation_documentary",
        "script_structure": "five_act_disaster",
        "bg_contrast_boost": 1.4,
        "bg_pool": "aviation_dramatic",
        "bg_blacklist": "-vacation -tourism -happy -celebration -luxury -business",
        "title_formula": "disaster_thriller",
        "video_duration_target": 105,
        "ethical_constraint": "always_end_with_safety_improvement",
        "cta_style": "moral_dilemma_question",
        "topics_queue_file": "topics_queue_aviation.txt",
    }
}
